"""initial schema: news and api_tokens

Revision ID: 34a0a7c31535
Revises: 
Create Date: 2026-06-03 17:04:57.070771+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34a0a7c31535'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Применить миграцию"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('source_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'scheduled', 'shown', 'archived', name='news_status'), nullable=False),
    sa.Column('scheduled_for', sa.Date(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('shown_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_news_schedule', 'news', ['scheduled_for', 'position'], unique=False)
    op.create_index('ix_news_status', 'news', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откатить миграцию"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_news_status', table_name='news')
    op.drop_index('ix_news_schedule', table_name='news')
    op.drop_table('news')
    op.drop_table('api_tokens')
    # ### end Alembic commands ###
    # Тип enum не удаляется автоматически вместе с таблицей в PostgreSQL
    sa.Enum(name='news_status').drop(op.get_bind(), checkfirst=True)
